{"level":"error","message":"Error in signUp: User already exists","timestamp":"2025-01-25T05:29:48.547Z","trace":"ConflictException: User already exists\n    at AuthService.signUp (/Users/saurabhnangia29719/Desktop/EasyGenerator/Backend/auth-service/src/modules/auth/services/auth.service.ts:27:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"Error in signUp: User already exists","timestamp":"2025-01-26T08:46:50.497Z","trace":"ConflictException: User already exists\n    at AuthService.signUp (/Users/saurabhnangia29719/Desktop/EasyGenerator/Backend/auth-service/src/modules/auth/services/auth.service.ts:28:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"Error in signIn: Invalid credentials","timestamp":"2025-01-26T08:47:22.453Z","trace":"UnauthorizedException: Invalid credentials\n    at AuthService.signIn (/Users/saurabhnangia29719/Desktop/EasyGenerator/Backend/auth-service/src/modules/auth/services/auth.service.ts:56:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
